name: Build Velox

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Build Windows
        shell: msys2 {0}
        run: |
          mkdir -p build
          g++ src/*.cpp -Iinclude -O2 -o build/velox.exe

      - uses: actions/upload-artifact@v4
        with:
          name: velox-windows
          path: build/velox.exe

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build Linux
        run: |
          mkdir -p build
          g++ src/*.cpp -Iinclude -O2 -o build/velox
          chmod +x build/velox

      - uses: actions/upload-artifact@v4
        with:
          name: velox-linux
          path: build/velox