name: Build Velox

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        if: matrix.os=='windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Install GCC
        if: matrix.os=='ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build Windows
        if: matrix.os=='windows-latest'
        shell: msys2 {0}
        run: |
          mkdir -p build
          g++ src/*.cpp -Iinclude -O2 -o build/velox.exe

      - name: Build Linux
        if: matrix.os=='ubuntu-latest'
        run: |
          mkdir -p build
          g++ src/*.cpp -Iinclude -O2 -o build/velox
          chmod +x build/velox

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: build/*

  release:
    needs: build
    if: startsWith(github.ref,'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare Release Files
        run: |
          mkdir release
          cp artifacts/windows-latest/velox.exe release/velox.exe
          cp artifacts/ubuntu-latest/velox release/velox

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/velox.exe
            release/velox